CREATE TABLE IF NOT EXISTS documentos (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    tipo VARCHAR(100),
    descricao TEXT,
    caminho_arquivo VARCHAR(512) NOT NULL,
    tamanho INTEGER,
    tipo_arquivo VARCHAR(100),
    data_upload TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    licitacao_id INTEGER NOT NULL REFERENCES licitacoes(id) ON DELETE CASCADE,
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE SET NULL, 
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS comentarios (
    id SERIAL PRIMARY KEY,
    texto TEXT NOT NULL,
    data TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    licitacao_id INTEGER NOT NULL REFERENCES licitacoes(id) ON DELETE CASCADE,
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE SET NULL, 
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_documentos_licitacao_id ON documentos(licitacao_id);
CREATE INDEX IF NOT EXISTS idx_comentarios_licitacao_id ON comentarios(licitacao_id);


ALTER TABLE empenhos
ADD COLUMN cidade VARCHAR(255),
ADD COLUMN uf VARCHAR(2);

ALTER TABLE entregas
ADD COLUMN empenho_id INTEGER;

ALTER TABLE entregas
ADD CONSTRAINT fk_empenho
FOREIGN KEY (empenho_id)
REFERENCES empenhos(id)
ON DELETE SET NULL 
ON UPDATE CASCADE;


